

























	var Resource = {
		common : {	
		    setMailCount:"可以设置的邮箱帐号数为空",
		    canInput:"您还可以输入",
		    character:"个字",
		    over:"已超出",
		    memo:"您无权操作此备忘",
		    contentToLong:"您输入的内容过长，请限制在5000字以内",	
		    selectstaff:"请选择人员",
			ok : "确定",
			cancel : "取消",
			retry : "重试",
			areyousure : "确定吗?",
			confirmTitle : "系统提示",	
	 		commonDelete : "删除",
	 		resume : "恢复",
			loginErrorUser : "必须录入登录帐号。",
			loginErrorPassword : "必须录入密码。",
			loginErrorNoValidatePW : "请输入验证码",
			loginRelogin : "请重新登录",
			errorInfo : "错误信息",
			servershutdown : "连接不上服务器，请稍后重试",
			operateFail : "操作失败",
			needAdminLogin : "对不起，只有系统管理员才有权访问。5秒钟后返回首页",
			serverBusy : "服务器忙，请稍后重试",
			searchNoContent : "搜索关键字不能为空",
			forbidFileTypes : '',
			descLess: "请输入描述内容",
			success : '操作成功',
			dwrloadMessage:"正在加载...",
			beginTimeLessEnd : "开始时间不能晚于结束时间，请重新选择",			
			error_subject : "请输入主题",
			organization : "组织结构",
			too_big_content : '内容太多，请精简',			
			errorduty : '请输入职务名称',
			pleaseinputcontent : '请输入内容',
			pleaseinputkey : '请输入关键字',
			jingjian : '精简',
			gengduo : '更多',
			backtoresult : '返回搜索结果',
			close : '关闭',
			back : '上一个',
			forward : '下一个',
			invalidModule : '您访问的模块不可用',
			backtoresult : '返回搜索结果',
			transfer:'转发消息',
			file_no_right:"文件传输服务已经关闭，请联系管理员或今目标客服",
			disk_no_more:"服务器存储空间不足，请联系管理员或今目标客服",
			sms_service_stop:"短信服务已被停止",
			add_success:"添加成功",
			region:"地区",
			logintime:"登录时间",
			companyName:"公司信息",
			phone:"联系电话",
			remark:"备注",
			select:"请选择",
			commonOrganization:"组织结构",
			userDefinedGroup:"自定义组",
			groupName:"请输入自定义组名",
			invalidUserSession:"当前页面用户会话已失效，请刷新页面载入新会话",
			attent1:"一般关注",
			attent2:"特别关注",
			mailSearch:"邮件搜索",
			attachSearch:"附件搜索",
			draftLeaveTip:"您的邮件已修改，是否放弃？",
			creator:"创建人",
			remarkTooLong:"备注长度不能大于60",
			remarkTooLong500:"备注长度不能大于500"
		},
		task : {
			task : "项目管理",
			myList : "项目管理",
			counselList : "协商列表",
			myView : "我浏览的项目",
			tasklist_str : "返回项目列表",
			counsellist_str : "返回协商列表",
			landmarklist_str : "返回阶段性成果列表",
			waitlist_str : "返回待办事宜列表",
			myBrowseTask : "返回我浏览的项目列表",
			task_baseic_now_state_submit_principal : "项目的基本信息已经建立，并提交给负责人，等待负责人接受此项目",
			task_baseic_now_state_noexecuter : "负责人已经接受此项目，还没有设置执行人",
			task_baseic_now_state_newtask : "正在新建项目",
			task_baseic_now_state_doing : "项目正在执行中，执行人已经设置",
			task_baseic_now_state_abandoned : "此项目已撤销",
			task_baseic_now_state_pause : "此项目已暂停",
			task_baseic_now_state_over : "此项目已结束",			
			task_baseic_now_state_noevaluate : "还没有对项目进行评估",	  
			task_person_nohave_principal : "没有负责人",
			task_person_nohave_executer : "没有执行人",
			task_person_setPrincipal : "设置负责人",
			task_person_modifyPrincipal : "编辑负责人",
			task_person_modifyExecuter : "编辑执行人",
			task_person_setExecuter :  "设置执行人",	
			task_landmark : "阶段性成果",
			task_commission : "待办事宜",
			task_resourse : "资源",
			task_file : "文档",
			task_event : "事件",
			task_counsel : "协商",
			task_evaluate : "评估",
			task_event_audit_auditing : "审核",
			task_basic : "项目概览",	
			task_event_updatetask_suspending : "撤销项目",
			task_event_updatetask_reset : "恢复项目",
			task_event_updatetask_abandoned : "撤销项目",
			task_person_submitToPrincipal : "提交给负责人",
			task_person_principal_applyComplete : "申请完成",
			task_person_executor_applyComplete : "申请完成",
			task_person_pricipal_accept : "接受项目",
			task_person_shifttask : "转移项目",
			task_person_activeTask : "重新激活项目",
	 		task_basic_updatetask_baseinfo : "修改项目",
	 		description_big : "描述内容太多，请精简",
	 		task_person_set_executer_no : "您没有选择“执行人”，请选择",
	 		task_person_set_executer_same : "您没有编辑“执行人”人员名单",
	 		task_person_set_initiator_info_same : "您选择的人，他/她已经是发起人，请重新选择",
	 		task_person_set_initiator_info_noperson : "请选择发起人",
	 		task_editreason_description_1 : "请输入暂停此项目的原因",
	 		task_editreason_description_2 : "请输入撤销此项目的原因",
	 		task_editreason_description_3 : "请输入恢复此项目的原因",
	 		task_editreason_description_4 : "请输入激活此项目的原因",
	 		task_editreason_description_5 : "请输入重新编辑基本信息的原因",
	 		task_editreason_description_6 : "请输入重新编辑发起人的原因",
	 		task_editreason_description_7 : "请输入重新编辑负责人的原因",
	 		task_editreason_description_8 : "请输入重新编辑执行人的原因",
	 		task_editreason_description_9 : "请输入转移执行人的原因",
	 		task_person_set_principal_info_same : "您选择的人，他/她已经是负责人，请重新选择",
	 		task_person_set_principal_info_noperson : "请选择负责人",
	 		task_basic_updatetask_error_noselectprincipal : "请选择并添加负责人",
	 		task_basic_updatetask_error_noselectexecuter : "请选择并添加执行人",
	 		task_basic_updatetask_error_name : "请输入项目名称",
	 		task_basic_updatetask_error_description : "请输入具体目标",
	 		task_basic_updatetask_error_start_time : "请选择项目开始时间",
	 		task_basic_updatetask_error_over_time : "请选择项目结束时间",
	 		task_basic_updatetask_error_noprincipal : "请设置负责人",
	 		task_basic_updatetask_error_noexecuter : "请设置执行人",
	 		task_person_shifttask_error_out : "请选择项目交出人",
	 		task_person_shifttask_error_in : "请选择项目接收人",
	 		task_person_shifttask_error_same2 : "已经是执行人员了，请重新选择项目接收人",
	 		task_person_shifttask_error_same : "项目接收人，项目交出人不能是同一个人，请重新选择",
	 		task_person_shifttask_select_out2 : "项目交出人:&nbsp;",
	 		task_person_shifttask_select_in2 : "项目接收人:&nbsp;",
	 		task_file_new_error_name : "请输入项目描述文档的名称",
	 		task_file_new_error_annex : "请选择项目描述文档的附件"
		},
		worklog : {  
			worklog : "工作日志",
			mylog : "我的日志",
			latestComment : "最新评论",
			newContentError : "日志内容，附件不能同时为空，请重新操作",
			editErrorBeforeSave : "请先提交已经存在的内容，再尝试此操作",
			attachmentPathError : "上传文件的路径错误",
			notExistContent : "评论内容不能为空",
			tooBigSizeComment : "“评论”内容太多，请精简",
			tooBigSizeLog : "日志内容太多，请精简",
			fileTypeWrong : "不允许此种类型文件的上传",
			week1 : "星期日",
			week2 : "星期一",
			week3 : "星期二",
			week4 : "星期三",
			week5 : "星期四",
			week6 : "星期五",
			week7 : "星期六"			
		},
		im : {
			im : "沟通平台",
			msgChat : "沟通窗口",
			msgSend : "广播消息",
			fileSend : "发送文件",
			title : "今目标企业工作平台",
			alert : "请注意，有消息了",
			noremessage : "此员工已经停用，不能回复",
			selectfile : "您选择的文件是 :",
			searchtext : "输入姓名，用户名，手机...",
			searchresult : "搜索结果",
			exception : "上传文件过程中出现异常，请重新上传",
			fail : "操作失败",
			filelength : "文件上传失败，文件大小超过系统限制20MB",
			filefail : "上传文件失败",
			fileprocess : "上传进度 :",
			filespeed : "上传速度 :",
			fileprocess : "上传进度 :",
			filetoSelect : "请选择一个文件",			
			remaintime : "剩余时间 :",
			hour : "小时",
			second : "秒",
			minute : "分",
			detail : "详情",
			wait : "等待",
			moreuser : "多人",
			willsend : "您要发送文件",
			give : "给",
			cancel : "文件已经取消上传",
			waitupload : "文件正在等待上传， 请稍候.",
			finishupload : "文件已经上传完毕",
			min5second : "上传的剩余时间小于5秒，不允许取消上传",
			finish : "完成",
			canceled : "已取消",
			error : "文件上传发生错误，取消失败",
			cancelfinish : "需要取消的文件已经发送完毕",
			user : "用户",
			nozore : "文件大小不能为0",
			orgByUser : "按员工",
			orgByDept : "按部门",
			orgByDuty : "按职务",
			orgByDeptDuty : "按部门职务",
			filter : "过滤:",
			errorStop : "服务器没有响应，已经终止此文件上传",
			onlineUser : "在线用户",
			needLogin : "您已经成功登录企业管理系统。确定要立即登录即时通讯吗？",
			groupChatEnd : "结束会话",
			revert : "回复",
			cancelRevert : "取消回复",
			sendMsg : "广播回复内容",
			nouser : "已选择的对象中没有人员，或者只包含自己",
			ubCommSendMsg : "发消息",
			ubCommSendMail : "发邮件",
			ubCommLookInfo : "看资料",
			ubCommCheckOSTip : "因您的操作系统不支持，<br>您暂时不能使用该功能！"
		},	
		setup : {
			eg : "公告栏",
			descriptionBig : "职务描述信息太多，请按说明精简",
			dutyNameKong : "职务名称不能是空，也不能是空格，请编辑",
			dutyNameIll : "职务名称不合法，请编辑",
			dutyNameDup : "职务名称重复，请编辑",
			os : {
				stopUser : "停用",
				departmentNew : "新建部门",
				deptError : "请输入部门名称，部门名称不能为空，也不能是空格",
				deptNameIll : "您输入的部门名称不合法",
				deptDesBig : "部门描述信息太多，请按说明精简",
				stopcause : "请输入停用原因",
				loginName : "请输入登录名",
				loginNameIll : "登录名不允许含有非法字符",
				tooShort : "您密码的位数少于8位，请重新输入",
				differ : "您两次输入的密码不一致，请重新输入",
				firstName : "请输入姓",
				firstNameIll : "姓的输入不正确，请重新输入",
				lastName : "请输入名",
				lastNameIll : "名的输入不正确，请重新输入",
				email : "电子邮箱的格式不正确，请重新输入",
				graduateDate : "毕业时间格式不正确，请按说明重新输入",
				remark : "备注内容太多，请精简",
				mobilesynError : "“移动电话”输入不合法",
				deptmentError : "您所选择的部门还没有提交，请提交",
				notChooseDetp : "请选择部门"
				
			},
			ca : {
				infoNameError : "请输入企业名称",
				infoAliasError : "请输入企业简称",
				infoCreatedateError : "企业成立时间的格式不正确，请按说明重新输入",
				moreInfoAddressError : "请输入企业通讯地址",
				moreInfoZipcodeError : "请输入邮政编码",
				moreInfoNameError : "请输入姓名",
				moreInfoPhoneError : "请输入公司电话",
				moreInfoMobileError : "请输入移动电话",
				moreInfoFaxError : "请输入传真",
				moreInfoEmail : "电子邮箱的格式不正确，请重新输入",
				data : "企业资料",
				info : "企业信息",
				baseinfo : " 基本信息",
				moremsg : " 附加信息 ",
				setcommonly : "常规设置",
				setlanguage : " 设置语言",
				settimezone : " 设置时区",
				settask : "项目相关",
				setblogtimeinterval : "设置日志间隔",
				awoke : "事件提醒",
				eicmsawoke : " 即时消息提醒",
				emailawoke : "邮件提醒",
				log_interval_zero : " 日志间隔不能是0",
				setup : " 状态设置",
				knowledgeAuditSetup : "设置知识发布方式"
			},
			de : {
				number : "???setup.de.number???",
				name : "???setup.de.name???",
				worknumber : "???setup.de.worknumber???"
			},
			sort : {
				changeType : "是否要恢复最后一次自定义排序吗？如果单击取消，自定义排序将恢复默认值(按拼音排序)",
				dutyList : "职务列表"
			}
		},
		eimhttp : {
			noduty : "未分配职务",
			root : "根",
			sender : "发送者",
			time : "时间",
			operate_time : "操作时间",			
			broadcastMsg : "广播消息",
			teamChat : "组聊",
			quitChat : "退出会话",
			initiater : "发起人",
			initiaterCloseChat : "已经关闭多人沟通",
			enterChat : "进入会话",
			offlineMsg : "离线消息",
			userStop : "对方用户已经被停用了",
			file : "文件:&nbsp;",
			uploadFail : "上传失败",
			clienthavelogin : "您已经在客户端上登录即时通讯系统，现在要重新登录吗？",
			webhavelogin : "您已经在别的网页上登录即时通讯系统，现在要重新登录吗？",
			smszf : "短信内容",
			im_status_0 : "离线",
			im_status_10 :"联机",
			im_status_20 :"离开",
			im_status_21 :"马上回来",
			im_status_22 :"正在开会",
			im_status_23 :"外出就餐",
			im_status_30 :"忙碌",
			im_status_31 :"通话中",
			im_manage_sms_center :"短信总机",
			operator :"操作人",
			receiver :"接收人",
			author_org :"原作者",
			transfer_from :"来源",
			content :"内容",
			subject :"主题",
			plan :"我的计划",
			forum :"论坛",
			employee_all :"公司全体员工",
			transmit_time :"转发时间",
			transmit_user :"转发人",
			online_client_my :"我的访客",
			online_client :"访客",
			online_server :"客服人员",
			unknown_corp : "未知企业"
		},
		tree : {
			way : "(离开)",
			busy : "(忙碌)",
			online : "(在线)",
			offline : "(离线)",
			noUser : "没有人员",
			noTeam : "没有组，您可以在客户端创建组",
			loading : "正在加载",
			noSelectUser : "没有可选人员　"
		},
		help : {
			info : "帮助信息",
			main : "帮助中心",
			welcom : "欢迎您使用今目标帮助中心",
			navigator : "帮助导航",
			workbench : "工作台",
			mywork : "我的工作",
			enterpriceDoor : "公告栏",
			mytask : "项目管理",
			milestone : "阶段性成果",
			commun : "协商列表",
			wait : "待办事宜",
			myViewTask : "我浏览的项目",
			worklog : "工作日志",
			myworklog : "我的日志",
			newReview : "最新评论",
			im : "沟通平台",
			msg : "广播消息",
			sendFile : "发送文件",
			task : "项目管理"
		},
		knowledge : {
		    chooseKnowledge: "请选择一个知识",
		    cancled: "该知识点已被撤销",
			searchkey : "请输入知识关键字",
			my : "我的知识",
			ep : "知识库"
		},
		editor : {
			say : "说",
			promptImg : "请输入图片网址(http://i.tom.com/a.jpg),不能使用本系统的图片",
			alertLinkLabel : "请选择需要链接的文字",
			promptLinkUrl : "请输入超链接,如 http://www.jingoal.com"
		},
		validate : {
			required : "这是必填项,空格无效",
			number : "请输入有效的数字",
			digits : "请输入合法的数",
			alpha : "请不要输入字母以外的字符",
			alphanum : "这里只允许输入数字和字母",
			email : "请输入合法的email地址",
			date_au : "请按照下面格式输入日期: 日/月/年. 例如 17/03/2009",
			selection : "这是必选项",
			oneRequired : "请在上面选择一项",
			lawless : "输入的内容中不应该包含下列字符：,;\'\"@<>%\\",
			phone : "手机号码不合法",
			uniqueDeptname : "???validate.uniqueDeptname???",
			itemLimit : "至少选择一项",
			notMatch : "两次输入的新密码不一致",
			lengthRange : function(minLength, maxLength) {
				var msg = "长度应该在{minLength}-{maxLength}之间";
				msg = msg.replace("{minLength}", minLength);
				msg = msg.replace("{maxLength}", maxLength);
				return msg;
			},
			url:"请输入合法的网址"
		},
		fileUpload : {
			upperLimit : "附件数量已到上限!",
			remove : "删除",
			repeat : "所选文件重复了，请重新选择!"
		},
		fancyUpload: {
			duplicate : '文件 "{name}" 已存在，不准许重复添加。',
			cancelTitle : '单击此处来取消和移除这个提示',
			sizeLimitMin:'文件 "{name}" ({size}) 长度太小，最小文件长度是 {fileSizeMin}。', 
			sizeLimitMax : '文件 "{name}" ({size}) 长度太大，最大文件长度是 {fileSizeMax}。',
			selectLimit : '当前最多可以选择{size}个文件'
		},
		online : {
			tree : {
				system : "系统设置",
				service : "客服管理",
				group  :  "客服分组",
				problem : "问题类型设置",
				style : "风格设置",
				invite : "邀请窗口设置",
				float : "浮动图标设置",
				chat : "会话窗口设置",
				dialog : "会话提示设置",
				message : "留言信息设置",
				code : "服务代码"
			},
			addSucc : "添加成功",
			visitor :"游客"
		},
		relogin : {
			password : "密　　码",
			user : "登录帐号",
			please : "请登录"
		},
		approve : {
		    noApply:"不能选择申请人", 
		    chooseApprove:"请选择一个申请单",
			approvePlepeoNotRight : "审批人不能为申请人",
			approvePeopleMust : "您必须选择一个人员",
			chooseApprover:"请选择审批人",
			dellevel:"确认删除该级别吗？",
			noApprover:"找不到审批人",
			flowNameInput:"名称不能超过64个字",
			noFlowLevel:"级别名称不能为空",
			noFlow:"该流程不存在或已被删除",
			noDutyApprover:"职位下没有人员",
			deleteSure:"您确定要删除此类型吗？",
			noEmpty:"不能为空",
			noLength:"长度不能大于16个字符",
			max16:"名称不能超过16个字",
			trans:"选择审批人",
			error:"此项为必填项"
		} 
	};